- name: Install haproxy and keepalived
  apt:
    update_cache: false
    name:
      - keepalived
      - haproxy
    state: present
  when: "'kubernetes_masters' in group_names"
  tags:
  - haproxy

- name: set keepalive role and priority for primary master
  set_fact:
    LEO_CLUSTER_KEEPALIVE_ROLE: 'MASTER'
    LEO_CLUSTER_KEEPALIVE_PRIORITY: 100
  when: 'inventory_hostname == groups["kubernetes_masters"][0]'
  tags:
  - haproxy

- name: set keepalive role for other masters
  set_fact:
    LEO_CLUSTER_KEEPALIVE_ROLE: 'BACKUP'
    LEO_CLUSTER_KEEPALIVE_PRIORITY: 80
  when: "'kubernetes_masters' in group_names and inventory_hostname != groups['kubernetes_masters'][0]"
  tags:
  - haproxy

- name: copy haproxy checking script
  template:
    src: check_haproxy.sh
    dest: /etc/keepalived/check_haproxy.sh
    mode: "a+x"
  when: "'kubernetes_masters' in group_names"
  tags:
  - haproxy

- name: install keepalived conf file
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  when: "'kubernetes_masters' in group_names"
  tags:
  - haproxy

- name: install haproxy conf file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  when: "'kubernetes_masters' in group_names" 
  tags:
  - haproxy

- name: enable haproxy and keepalived service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - haproxy
    - keepalived
  when: "'kubernetes_masters' in group_names"
  tags:
  - haproxy
