#- name: install calico operator
#  k8s:
#    state: present
#    src: "{{ role_path }}/files/tigera-operator.yaml"
#    kubeconfig: "/etc/kubernetes/admin.conf"
#  when: >
#    inventory_hostname == groups["kubernetes_masters"][0] and
#    LEO_CLUSTER_CNI == "calico"
#
#- name: generate calico crds
#  k8s:
#    state: present
#    definition: "{{ lookup('template', role_path + '/files/custom-resources.yaml') }}"
#    kubeconfig: "/etc/kubernetes/admin.conf"
#    wait_timeout: 600
#    wait: yes
#  when: >
#    inventory_hostname == groups["kubernetes_masters"][0] and
#    LEO_CLUSTER_CNI == "calico"
- name: download calico yaml file
  command: "wget https://docs.projectcalico.org/manifests/calico.yaml -O /tmp/calico.yaml"
  when: >
    inventory_hostname == groups["kubernetes_masters"][0] and
    LEO_CLUSTER_CNI == "calico"

- name: install calico
  k8s:
    state: present
    src: "/tmp/calico.yaml"
    kubeconfig: "/etc/kubernetes/admin.conf"
  when: >
    inventory_hostname == groups["kubernetes_masters"][0] and
    LEO_CLUSTER_CNI == "calico"

- name: install flannel
  k8s:
    state: present
    definition: "{{ lookup('template', role_path + '/files/kube-flannel.yml') }}"
    kubeconfig: "/etc/kubernetes/admin.conf"
    wait_timeout: 600
    wait: yes
  when: >
    inventory_hostname == groups["kubernetes_masters"][0] and
    LEO_CLUSTER_CNI == "flannel"

- name: join nodes 
  command: "{{ basic_command }}"
  when: >
          inventory_hostname in groups["kubernetes_workers"] and
          not node_initialized.stat.exists

- name: create .kube folder
  command: mkdir ~/.kube
  when: >
          inventory_hostname == groups["kubernetes_masters"][0]

- name: copy kubeconfig file to root user directory
  command: cp /etc/kubernetes/admin.conf /root/.kube/config
  when: >
          inventory_hostname == groups["kubernetes_masters"][0]

- name: auto approve kubelet-serving csr
  script: "{{ role_path }}/files/approve_csr.sh"
  when: >
          inventory_hostname == groups["kubernetes_masters"][0]
