---
- name: Prerequisites
  include_tasks: pre-requisites.yaml

- name: setup API High availabilities
  include_tasks: haproxy-setup.yaml

- name: Init masters
  include_tasks: init-masters.yaml

- name: Init nodes
  include_tasks: init-nodes.yaml
